#!/usr/bin/env bash
#
# Coach Script: Generate Workshop Summary Report
#
# Usage: ./scripts/generate-workshop-report.sh > workshop-summary-YYYY-MM-DD.md
#
# Description: Generates a comprehensive workshop summary report including
# student statistics, progress, and badge completion.

set -euo pipefail

# Fetch all remote branches
git fetch --all --quiet

# Get workshop metadata
TOTAL_STUDENTS=$(git branch -r | grep -c student/ || echo "0")
REPORT_DATE=$(date '+%Y-%m-%d')
REPORT_TIME=$(date '+%H:%M:%S')

# Generate Markdown report
cat <<EOF
# Workshop Summary Report

**Generated**: $REPORT_DATE $REPORT_TIME
**Total Students**: $TOTAL_STUDENTS

---

## 📊 Student Statistics

| Metric | Count |
|--------|-------|
| Total Students | $TOTAL_STUDENTS |
| Active (pushed in last 24h) | $(git branch -r | grep student/ | while read -r branch; do git log --since="24 hours ago" --oneline "$branch" 2>/dev/null | head -1; done | grep -c . || echo "0") |
| Completed Level 101 PRs | $(gh pr list --label "level-101" --state merged 2>/dev/null | grep -c . || echo "N/A") |
| Pending PRs | $(gh pr list --label "workshop" --state open 2>/dev/null | grep -c . || echo "N/A") |

---

## 👥 Student Progress

| Student | Branch | Commits | Last Activity | Status |
|---------|--------|---------|---------------|--------|
EOF

# Loop through student branches and add to table
for branch in $(git branch -r | grep student/ | sed 's/origin\///' | sort); do
    username=$(echo "$branch" | sed 's/student\///')
    commit_count=$(git rev-list --count "origin/$branch" 2>/dev/null || echo "0")
    last_activity=$(git log --format="%ar" --max-count=1 "origin/$branch" 2>/dev/null || echo "Never")

    # Determine status based on activity
    if [ "$commit_count" -ge 10 ]; then
        status="🟢 Active"
    elif [ "$commit_count" -ge 5 ]; then
        status="🟡 Progressing"
    else
        status="🔴 Needs Attention"
    fi

    echo "| $username | \`$branch\` | $commit_count | $last_activity | $status |"
done

# Continue with report
cat <<EOF

---

## 🎖️ Badge Completion

### Level 101: Foundations

| Block | Badge | Validation Command | Status |
|-------|-------|-------------------|--------|
| 1 | 🥉 Bronze | \`./scripts/workshop-check.sh block1\` | Manual verification required |
| 2 | 🥈 Silver | \`./scripts/workshop-check.sh block2\` | Manual verification required |
| 3 | 🥇 Gold | \`./scripts/workshop-check.sh block3\` | Manual verification required |
| 4 | ⚙️ Iron | \`./scripts/workshop-check.sh block4\` | Manual verification required |
| 5 | 🛡️ Steel | \`./scripts/workshop-check.sh block5\` | Manual verification required |
| 6 | 💎 Diamond | \`./scripts/workshop-check.sh block6\` | Manual verification required |

**Master Badge** (all 6 badges): Manual verification required

---

## 📝 Pull Requests

EOF

# List open PRs if gh is installed
if command -v gh &> /dev/null; then
    echo "### Open PRs"
    echo ""
    gh pr list --label "workshop" --state open 2>/dev/null || echo "_No open PRs or gh CLI not configured_"
    echo ""
    echo "### Recently Merged PRs"
    echo ""
    gh pr list --label "workshop" --state merged --limit 10 2>/dev/null || echo "_No merged PRs or gh CLI not configured_"
else
    echo "_GitHub CLI not installed - unable to fetch PR data_"
fi

# Recommendations
cat <<EOF

---

## 💡 Recommendations

**Students Needing Attention**:
$(for branch in $(git branch -r | grep student/ | sed 's/origin\///'); do
    username=$(echo "$branch" | sed 's/student\///')
    commit_count=$(git rev-list --count "origin/$branch" 2>/dev/null || echo "0")
    if [ "$commit_count" -lt 5 ]; then
        echo "- **$username** (only $commit_count commits)"
    fi
done)

**Next Steps**:
1. Review progress trackers for all students
2. Follow up with students showing low activity
3. Schedule 1-on-1 sessions for students needing extra help
4. Review and approve pending PRs

---

## 📞 Contact

For questions about this report, contact the workshop trainer.

**Report Version**: 1.0
**Generated by**: \`./scripts/generate-workshop-report.sh\`
EOF
